INSERT INTO PAIS (NOME,SIGLA) VALUES('Brasil', 'BRA');

INSERT INTO CIDADE (IBGE,NOME,PAIS_ID) VALUES('26', 'Pernambuco', 1);
INSERT INTO CIDADE (IBGE,NOME,PAIS_ID) VALUES('22', 'Piaui', 1);

INSERT INTO SITUACAO_SAUDE (SITUACAO) VALUES(1);

INSERT INTO VOLUNTARIO (PASSAPORTE,NOME_COMPLETO,IDADE,TELEFONE,EMAIL,TIPO_SANGUE,CIDADE_ID,SITUACAO_SAUDE_ID) VALUES('FS245798', 'Nome 01', 23, '92 9 9999-9999', 'email@email.com', 'O-', 1, 1);

